stem/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import url
from . import views
from .views import StudentCreateView, StudentListView, StudentDetailView
from django.conf import settings
from django.conf.urls.static import static


app_name = "stem"

urlpatterns = [
    #path('', views.home, name='home'),
    path('', StudentCreateView.as_view(), name='home'),
    path('manage-students/', StudentListView.as_view(), name='list-students'),
    path('profile/<int:pk>/', StudentDetailView.as_view(), name='student-details'),
    path('login/', auth_views.LoginView.as_view(template_name='stem/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='stem/logout.html'), name='logout'),
    #path('new/', PostCreateView.as_view(), name='post-create'),
    #path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    #path('result/', views.search, name='result'),
    #path('new/', views.post_create, name='post-create'),
    #url(r'post/(?P<id>\d+)/$', views.post_detail, name='post-detail'),
    #url(r'^like/$', views.like_post, name='like_post'),
]

stem_enrollment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stem.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stem/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import STUDENT_INFO


YN_CHOICES = [
        ('No', 'No'),
        ('Yes', 'Yes'),
    ]


EDUCATTAIN_CHOICES = [
        ('',''),
        ('Elementary Graduate', 'Elementary Graduate'),
        ('High School Graduate', 'High School Graduate'),
        ('College Graduate', 'College Graduate'),
        ('Vocational', 'Vocational'),
        ('Masters/Doctorate degree', 'Masters/Doctorate degree'),
        ('Did not attend school', 'Did not attend school'),
    ]


GRADE_CHOICES = [
        ('Grade 11', 'Grade 11'),
        ('Grade 12', 'Grade 12'),
    ]


LGRADE_CHOICES = [
        ('Grade 6', 'Grade 6'),
        ('Grade 7', 'Grade 7'),
        ('Grade 8', 'Grade 8'),
        ('Grade 9', 'Grade 9'),
        ('Grade 10', 'Grade 10'),
        ('Grade 11', 'Grade 11'),
        ('Grade 12', 'Grade 12'),
    ]


SCHOOLTYPE_CHOICES = [
        ('Public', 'Public'),
        ('Private', 'Private'),
    ]


SEMESTER_CHOICES = [
        ('1st', '1st'),
        ('2nd', '2nd'),
    ]


STRAND_CHOICES = [
        ('',''),
        ('Accountancy, Business and Management', 'ABM'),
        ('Humanities and Social Sciences', 'HUMSS'),
        ('Science, Technology, Engineering, and Mathematics', 'STEM'),
        ('General Academic Strand', 'GAS'),
    ]


TRACK_CHOICES = [
        ('',''),
        ('Academic Track', 'Academic Track'),
        ('Technical-Vocational-Livelihood', 'Technical-Vocational-Livelihood'),
        ('Sports Track', 'Sports Track'),
        ('Arts and Design Track', 'Arts and Design Track'),
    ]

SEX_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]


EMPSTATUS_CHOICES = [
        ('Full time', 'Full time'),
        ('Part time', 'Part time'),
        ('Self employed', 'Self employed'),
        ('Unemployed due to ECQ', 'Unemployed due to ECQ'),
        ('Not working', 'Not working'),
    ]


YEARS= [x for x in range(1990,2020)]


class StudentRegisterForm(forms.ModelForm):
    school_year1 = forms.CharField(label='A1. School Year')
    school_year2 = forms.CharField(label='-----------')
    wlrn = forms.ChoiceField(label='A2. Has LRN', choices=YN_CHOICES)
    returning = forms.ChoiceField(label='A3. Returning (Balik eskwela)', choices=YN_CHOICES)
    grade_level_to_enroll = forms.ChoiceField(label='A4. Grade Level to Enroll', choices=GRADE_CHOICES)
    last_grade_level_com = forms.ChoiceField(label='A5. Last grade level completed', choices=LGRADE_CHOICES)
    last_school_year_com = forms.CharField(label='A6. Last school year completed')
    school_id_to_enroll = forms.CharField(label='A12. School ID')
    last_school_attended = forms.CharField(label='A7. Last School Attended')
    school_id = forms.CharField(label='A8. School ID')
    school_address = forms.CharField(label='A9. School Address')
    school_type = forms.ChoiceField(label='A10. School Type', choices=SCHOOLTYPE_CHOICES)
    school_to_enroll_in = forms.CharField(label='A11. School to enroll in')
    school_address_to_enroll = forms.CharField(label='A13. School Address')
    semester = forms.ChoiceField(label='A14. Semester', choices=SEMESTER_CHOICES)
    track = forms.ChoiceField(label='A15. Track', choices=TRACK_CHOICES)
    strand = forms.ChoiceField(label='A16. Strand', choices=STRAND_CHOICES, required=False)

    psa_cer_no = forms.CharField(label='B1. PSA Birth Certificate No. (if available upon enrolment)', required=False)
    lrn = forms.CharField(label='B2. Learners Reference Number (LRN)')
    last_name = forms.CharField(label='B3. Last Name')
    first_name = forms.CharField(label='B4. First Name')
    middle_name = forms.CharField(label='B5. Middle Name', required=False)
    extension_name = forms.CharField(label='B6. Extension Name', required=False)
    birthdate = forms.DateField(widget=forms.SelectDateWidget(years=YEARS))
    age = forms.CharField(label='B8. Age')
    sex = forms.ChoiceField(label='B9. Sex', choices=SEX_CHOICES)
    ip = forms.ChoiceField(label='B10. Belonging to Indigenous People (IP)', choices=YN_CHOICES, required=False)
    ip_specify = forms.CharField(label='B11. If yes, please specify:', required=False)
    mother_tongue = forms.CharField(label='B12. Mother tongue', required=False)
    religion = forms.CharField(label='B13. Religion', required=False)
    special_ed_needs = forms.ChoiceField(label='B14. Does the learner have special education needs?', choices=YN_CHOICES, required=False)
    speed_needs_specify = forms.CharField(label='B15. If yes, please specify:', required=False)
    technology_devices = forms.ChoiceField(label='B16. Do you have any assistive technology devices available at home?', choices=YN_CHOICES, required=False)
    technology_devices_specify = forms.CharField(label='B17. If yes, please specify:', required=False)
    house_number_and_street = forms.CharField(label='B18. House number and street', required=False)
    barangay = forms.CharField(label='B19. Barangay')
    city_municipality = forms.CharField(label='B20. City/Municipality')
    province = forms.CharField(label='B21. Province')
    region = forms.CharField(label='B22. Region')
    
    father_full_name = forms.CharField(label='C1. Father Full name (surname, name, middle name)')
    father_educ_attainment = forms.ChoiceField(label='C2. Father Educational Attainment', choices=EDUCATTAIN_CHOICES)
    father_working_from_home_due_to_ecq = forms.ChoiceField(label='C4. Working from home due to_ECQ', choices=YN_CHOICES)
    mother_full_name = forms.CharField(label='C7. Mother Full name (surname, name, middle name)')
    mother_educ_attainment = forms.ChoiceField(label='C8. Mother Educational Attainment', choices=EDUCATTAIN_CHOICES)
    mother_working_from_home_due_to_ecq = forms.ChoiceField(label='C10. Working from home due to_ECQ', choices=YN_CHOICES)
    guardian_full_name = forms.CharField(label='C13. Guardian Full name (surname, name, middle name)', required=False)
    guardian_educ_attainment = forms.ChoiceField(label='C14. Guardian Educational Attainment', choices=EDUCATTAIN_CHOICES)
    guardian_working_from_home_due_to_ecq = forms.ChoiceField(label='C16. Working from home due to_ECQ', choices=YN_CHOICES)

    image = forms.FileInput()
    birth_certificate = forms.FileField(label='Birth Certificate', required=False)
    form_137 = forms.FileField(label='School Card', required=False)
    
    class Meta:
        model = STUDENT_INFO
        fields = [
            'school_year1',
            'school_year2',
            'wlrn',
            'returning',
            'grade_level_to_enroll',
            'last_grade_level_com',
            'last_school_year_com',
            'last_school_attended',
            'school_id',
            'school_address',
            'school_type',
            'school_to_enroll_in',
            'school_id_to_enroll',
            'school_address_to_enroll',
            'semester',
            'track',
            'strand',

            'psa_cer_no',
            'lrn',
            'last_name',
            'first_name',
            'middle_name',
            'extension_name',
            'birthdate',
            'age',
            'sex',
            'ip',
            'ip_specify',
            'mother_tongue',
            'religion',
            'special_ed_needs',
            'speed_needs_specify',
            'technology_devices',
            'technology_devices_specify',
            'house_number_and_street',
            'barangay',
            'city_municipality',
            'province',
            'region',
            
            'father_full_name',
            'father_educ_attainment',
            'father_employment_status',
            'father_working_from_home_due_to_ecq',
            'father_contact',
            'mother_full_name',
            'mother_educ_attainment',
            'mother_employment_status',
            'mother_working_from_home_due_to_ecq',
            'mother_contact',
            'guardian_full_name',
            'guardian_educ_attainment',
            'guardian_employment_status',
            'guardian_working_from_home_due_to_ecq',
            'guardian_contact',

            'image',
            'form_137',
            'birth_certificate',
        ]

stem/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import StudentRegisterForm
from .models import STUDENT_INFO
from django.views.generic import (DetailView, ListView, CreateView, TemplateView)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .filter_mixin import ListFilteredMixin
from .filters import StudentFilter

# Create your views here.
"""
def home(request):
    if request.method == 'POST':
        form = StudentRegisterForm(request.POST)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
            lrn = form.cleaned_data.get('lrn')
            messages.success(request, f'Submit Success')
            return redirect('stem:home')
    else:
        form = StudentRegisterForm()
    context={
        'form' : form,
    }
    return render(request, 'stem/enrol.html', context)"""



class StudentCreateView(SuccessMessageMixin, CreateView):
    model = STUDENT_INFO
    form_class = StudentRegisterForm
    success_message = "Thank you!"


class StudentListView(LoginRequiredMixin, ListFilteredMixin, ListView):
    model = STUDENT_INFO
    template_name = 'stem/list_student.html'
    context_object_name = 'students'
    paginate_by = 1
    filter_set = StudentFilter
    def get_queryset(self):
        qs = self.model.objects.all().order_by('last_name')
        student_filter = StudentFilter(self.request.GET, queryset=qs)
        return student_filter.qs


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = STUDENT_INFO
    template_name = 'stem/student_info_detail.html'

stem/templates/stem/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'stem/css/main.css' %}"
    />
    <title>Online Enrollment Form</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
      <a class="navbar-brand" href="#">
        <img src="{% static 'stem/img/cnhslogo.png' %}" width="30" height="30" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'stem:home' %}">Enroll Now</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'stem:list-students' %}">Manage Students</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-e">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
      {% block content %}{% endblock %}
    </div>
  </body>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
</html>

stem/templates/stem/list_student.html
{% extends "stem/base.html" %}
    {% load crispy_forms_tags %}{% load widget_tweaks %} {% load static %} {% block content %}
    <div class="manage-container">
        <h4>Filter:</h4>
        <form method="get" class="form-filter">
        <div class="row">
            <div class="form-group col-md-2 mb-0">
                <div class="input">
                    {{ filter.form.lrn.label_tag }}
                    {% render_field filter.form.lrn class="form-control" %}
                </div>
            </div>
            <div class="form-group col-md-2 mb-0">
                <div class="input">
                    {{ filter.form.last_name.label_tag }}
                    {% render_field filter.form.last_name class="form-control" %}
                </div>
            </div>
            <div class="form-group col-md-2 mb-0">
                <div class="input">
                    {{ filter.form.first_name.label_tag }}
                    {% render_field filter.form.first_name class="form-control" %}
                </div>
            </div>
            <div class="form-group col-md-2 mb-0">
                <div class="input">
                    {{ filter.form.track.label_tag }}
                    {% render_field filter.form.track class="form-control" %}
                </div>
            </div>
            <div class="form-group col-md-2 mb-0">
                <div class="input">
                    {{ filter.form.strand.label_tag }}
                    {% render_field filter.form.strand class="form-control" %}
                </div>
            </div>
            <div class="form-group col-md-2 mb-0">
                <div class="input">
                    {{ filter.form.grade_level_to_enroll.label_tag }}
                    {% render_field filter.form.grade_level_to_enroll class="form-control" %}
                </div>
            </div>
        </div>
        <div class="form-group col-md-2 mb-0">
                <div class="input">
                    {{ filter.form.sex.label_tag }}
                    {% render_field filter.form.sex class="form-control" %}
                </div>
            </div>
        <div class="frm-btn">
          <button type="submit" class="btn btn-primary">Search</button>
        </div>
      </form>
    <h4 class="mt-4">List of students</h4>
    <div class="table-responsive mt-2">
    <table class="table table-hover table-striped">
        <thead>
            <tr>
            <th scope="col">LRN</th>
            <th scope="col">Full name</th>
            <th scope="col">Track</th>
            <th scope="col">Strand</th>
            <th scope="col">Grade Level Enrol</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <th scope="row"><a href="{% url 'stem:student-details' student.id %}">{{ student.lrn }}</a></th>
                <td>{{ student.last_name }}, {{ student.first_name }} {{ student.middle_name }}</td>
                <td>{{ student.track }}</td>
                <td>{{ student.strand }}</td>
                <td>{{ student.grade_level_to_enroll }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="pagination">
        <div class="page">
            {% if is_paginated %}

            {% if page_obj.has_previous %}
                <a class="btn btn-outline-primary mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                <a class="btn btn-primary mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-primary mb-4" href="?page={{ num }}">{{ num }}</a>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

            {% endif %}
        </div>    
    </div>
    </div>
    </div>
    {% endblock %}

stem/templates/stem/login.html
{% extends "stem/base.html" %}
    {% load crispy_forms_tags %} {% load static %} {% block content %}
    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <div class="img-log">
            <!--<img src="{% static 'd_network/img/copypasta1.png' %}" alt="">-->
            <h3>Login</h3>
        </div>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Login</button>
      </div>
    </form>
    {% endblock %}

stem/templates/stem/logout.html
logout

stem/templates/stem/student_info_detail.html
{% extends "stem/base.html" %}
    {% load crispy_forms_tags %} {% load static %} {% block content %}
    {% endblock %}

stem/templates/stem/student_info_form.html
{% extends "stem/base.html" %}
    {% load crispy_forms_tags %} {% load static %} {% block content %}
    <div class="container">
    <div class="form-header-e">
      <div class="form-row">
        <div class="form-group col-md-2 mb-0">
            <img src="{% static 'stem/img/cnhslogo.png' %}" alt="">
        </div>
        <div class="form-group col-md-8 mb-0">
          <h2>LEARNER ENROLMENT AND SURVEY FORM</h2>
        </div>
        <div class="form-group col-md-2 mb-0">
            <img src="{% static 'stem/img/depedlogo.png' %}" alt="">
        </div>
      </div>
    </div>
    <div class="form-header-e-ins">
      <div class="form-group col-md-12 mb-0">
          <b>Instructions</b>
          <ol>
            <li>This enrolment survey shall be answered by the parent/guardian of the learner</li>
            <li>Please read the questions carefully and fill in all applicable spaces and write your answers legibly in CAPITAL letters. For items not applicable, write N/A.</li>
            <li>For questions/ clarifications, please ask for the assistance of the teacher/ person-in-charge.</li>
          </ol>
        </div>
    </div>
    <div class="content-login">
      <div class="master-login">
        <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
            <div class="img-log">
              <!--<img src="{% static 'd_network/img/copypasta1.png' %}" alt="">-->
            </div>
            <h4>A. Grade Level and School Information</h4>
            <div class="form-row">
              <div class="form-group col-md-2 mb-0">
                {{ form.school_year1|as_crispy_field }}
              </div>
              <div class="form-group col-md-2 mb-0">
                {{ form.school_year2|as_crispy_field }}
              </div>
              <div class="form-group col-md-4 mb-0">
                {{ form.wlrn|as_crispy_field }}
              </div>
              <div class="form-group col-md-4 mb-0">
                {{ form.returning|as_crispy_field }}
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-3 mb-0 border border-top-0 border-left-0 border-bottom-0 border-dark">
                {{ form.grade_level_to_enroll|as_crispy_field }}
                {{ form.last_grade_level_com|as_crispy_field }}
                {{ form.last_school_year_com|as_crispy_field }}
              </div>
              <div class="form-group col-md-4 mb-0 border border-top-0 border-left-0 border-bottom-0 border-dark">
                <div class="form-row">
                  <div class="form-group col-md-8 mb-0">
                    {{ form.last_school_attended|as_crispy_field }}
                  </div>
                  <div class="form-group col-md-4 mb-0">
                    {{ form.school_id|as_crispy_field }}
                  </div>
                </div>
                <div class="form-group col-md-13 mb-0">
                  {{ form.school_address|as_crispy_field }}
                </div>
                <div class="form-group col-md-13 mb-0">
                  {{ form.school_type|as_crispy_field }}
                </div>
              </div>
              <div class="form-group col-md-5 mb-0">
                <div class="form-row">
                  <div class="form-group col-md-8 mb-0">
                    {{ form.school_to_enroll_in|as_crispy_field }}
                  </div>
                  <div class="form-group col-md-4 mb-0">
                    {{ form.school_id_to_enroll|as_crispy_field }}
                  </div>
                </div>
                <div class="form-group col-md-13 mb-0">
                  {{ form.school_address_to_enroll|as_crispy_field }}
                </div>
              </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-2 mb-0">
                  {{ form.semester|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                  {{ form.track|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{ form.strand|as_crispy_field }}
                </div>
            </div>
            <h4>B. Student Information</h4>
            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                  {{ form.psa_cer_no|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                  {{ form.lrn|as_crispy_field }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                  {{ form.last_name|as_crispy_field }}
                </div>
                <div class="form-group col-md-3 mb-0">
                  {{ form.first_name|as_crispy_field }}
                </div>
                <div class="form-group col-md-3 mb-0">
                  {{ form.middle_name|as_crispy_field }}
                </div>
                <div class="form-group col-md-2 mb-0">
                  {{ form.extension_name|as_crispy_field }}
                </div>
            </div>
            
            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                <div class="form-row">
                  <div class="form-group col-md-12 mb-0">
                    {{ form.birthdate|as_crispy_field }}
                  </div>
                </div>
                  
                  <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                      {{ form.age|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                      {{ form.sex|as_crispy_field }}
                    </div>
                  </div>
                  
                  
                  {{ form.ip|as_crispy_field }}
                  {{ form.ip_specify|as_crispy_field }}
                  {{ form.mother_tongue|as_crispy_field }}
                  {{ form.religion|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                <h6 class="border border-top-0 border-left-0 border-right-0 mb-3 border-dark">For Learners with Special Education Needs</h6>
                  {{ form.special_ed_needs|as_crispy_field }}
                  {{ form.speed_needs_specify|as_crispy_field }}
                  {{ form.technology_devices|as_crispy_field }}
                  {{ form.technology_devices_specify|as_crispy_field }}
                </div>
            </div>
            <h6 class="border border-top-0 border-left-0 border-right-0 mb-3 border-dark">Address</h6>
            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                   {{ form.house_number_and_street|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                  {{ form.barangay|as_crispy_field }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                   {{ form.city_municipality|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{ form.province|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{ form.region|as_crispy_field }}
                </div>
            </div>
            <h4>C. Parent/Guardian Information</h4>
            <div class="form-row">
                <div class="form-group col-md-4 mb-0 border border-top-0 border-left-0 border-bottom-0">
                   {{ form.father_full_name|as_crispy_field }}
                   {{ form.father_educ_attainment|as_crispy_field }}
                   {{ form.father_employment_status|as_crispy_field }}
                   {{ form.father_working_from_home_due_to_ecq|as_crispy_field }}
                   {{ form.father_contact|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0 border border-top-0 border-left-0 border-bottom-0">
                  {{ form.mother_full_name|as_crispy_field }}
                  {{ form.mother_educ_attainment|as_crispy_field }}
                  {{ form.mother_employment_status|as_crispy_field }}
                  {{ form.mother_working_from_home_due_to_ecq|as_crispy_field }}
                  {{ form.mother_contact|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{ form.guardian_full_name|as_crispy_field }}
                  {{ form.guardian_educ_attainment|as_crispy_field }}
                  {{ form.guardian_employment_status|as_crispy_field }}
                  {{ form.guardian_working_from_home_due_to_ecq|as_crispy_field }}
                  {{ form.guardian_contact|as_crispy_field }}
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4 mb-0">
                   {{ form.image|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{ form.birth_certificate|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                  {{ form.form_137|as_crispy_field }}
                </div>
            </div>
          </fieldset>
          <div class="form-group">
            <button class="btn btn-primary" type="submit">Submit</button>
          </div>
        </form>
      </div>
    </>
    </div>
    {% endblock content %}